openapi: 3.0.3
info:
  title: PBI Analyzer API
  version: 1.0.0
  description: REST API for Power BI Best Practices Analyzer & AI Auto-Fix Web App

servers:
  - url: http://localhost:3001/api
    description: Local development server

paths:
  # ─────────────────────────────────────────────
  # Connection
  # ─────────────────────────────────────────────
  /connection/instances:
    get:
      operationId: listInstances
      summary: List local Power BI Desktop instances
      tags: [Connection]
      responses:
        "200":
          description: List of available PBI Desktop instances
          content:
            application/json:
              schema:
                type: object
                properties:
                  instances:
                    type: array
                    items:
                      $ref: "#/components/schemas/PbiInstance"

  /connection/connect:
    post:
      operationId: connect
      summary: Connect to a Power BI Semantic Model
      tags: [Connection]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ConnectRequest"
      responses:
        "200":
          description: Connection established
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ConnectionStatus"
        "400":
          $ref: "#/components/responses/BadRequest"
        "502":
          description: Cannot reach Power BI Desktop
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

  /connection/status:
    get:
      operationId: getConnectionStatus
      summary: Get current connection status
      tags: [Connection]
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ConnectionStatus"

  /connection/disconnect:
    post:
      operationId: disconnect
      summary: Disconnect from current Semantic Model
      tags: [Connection]
      responses:
        "200":
          description: Disconnected
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean

  # ─────────────────────────────────────────────
  # Analysis
  # ─────────────────────────────────────────────
  /analysis/run:
    post:
      operationId: runAnalysis
      summary: Run best practices analysis on connected model
      tags: [Analysis]
      responses:
        "200":
          description: Analysis started (returns run ID for polling)
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/AnalysisRun"
        "409":
          description: Analysis already in progress
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "422":
          description: No model connected
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

  /analysis/runs:
    get:
      operationId: listAnalysisRuns
      summary: List all analysis runs
      tags: [Analysis]
      parameters:
        - name: limit
          in: query
          schema:
            type: integer
            default: 10
        - name: offset
          in: query
          schema:
            type: integer
            default: 0
      responses:
        "200":
          content:
            application/json:
              schema:
                type: object
                properties:
                  runs:
                    type: array
                    items:
                      $ref: "#/components/schemas/AnalysisRun"
                  total:
                    type: integer

  /analysis/runs/{runId}:
    get:
      operationId: getAnalysisRun
      summary: Get a specific analysis run with its findings
      tags: [Analysis]
      parameters:
        - $ref: "#/components/parameters/RunId"
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/AnalysisRunDetail"
        "404":
          $ref: "#/components/responses/NotFound"

  # ─────────────────────────────────────────────
  # Findings
  # ─────────────────────────────────────────────
  /analysis/runs/{runId}/findings:
    get:
      operationId: listFindings
      summary: List findings for an analysis run (with filters)
      tags: [Findings]
      parameters:
        - $ref: "#/components/parameters/RunId"
        - name: severity
          in: query
          schema:
            type: integer
            enum: [1, 2, 3]
          description: "Filter by severity: 1=Info, 2=Warning, 3=Error"
        - name: category
          in: query
          schema:
            type: string
            enum:
              - Performance
              - DAX Expressions
              - Error Prevention
              - Maintenance
              - Naming Conventions
              - Formatting
        - name: fixStatus
          in: query
          schema:
            type: string
            enum: [UNFIXED, IN_PROGRESS, FIXED, FAILED]
        - name: sortBy
          in: query
          schema:
            type: string
            enum: [severity, category, fixStatus, createdAt]
            default: severity
        - name: sortOrder
          in: query
          schema:
            type: string
            enum: [asc, desc]
            default: desc
        - name: limit
          in: query
          schema:
            type: integer
            default: 50
        - name: offset
          in: query
          schema:
            type: integer
            default: 0
      responses:
        "200":
          content:
            application/json:
              schema:
                type: object
                properties:
                  findings:
                    type: array
                    items:
                      $ref: "#/components/schemas/Finding"
                  summary:
                    $ref: "#/components/schemas/FindingSummary"
                  total:
                    type: integer

  /findings/{findingId}:
    get:
      operationId: getFinding
      summary: Get a specific finding with fix details
      tags: [Findings]
      parameters:
        - $ref: "#/components/parameters/FindingId"
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/FindingDetail"
        "404":
          $ref: "#/components/responses/NotFound"

  # ─────────────────────────────────────────────
  # AI Fix
  # ─────────────────────────────────────────────
  /findings/{findingId}/fix:
    post:
      operationId: triggerFix
      summary: Trigger AI auto-fix for a finding
      tags: [AI Fix]
      parameters:
        - $ref: "#/components/parameters/FindingId"
      responses:
        "200":
          description: Fix initiated
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/FixSession"
        "404":
          $ref: "#/components/responses/NotFound"
        "409":
          description: Fix already in progress or finding already fixed
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

  /findings/{findingId}/fix/session:
    get:
      operationId: getFixSession
      summary: Get the AI fix session details for a finding
      tags: [AI Fix]
      parameters:
        - $ref: "#/components/parameters/FindingId"
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/FixSessionDetail"
        "404":
          $ref: "#/components/responses/NotFound"

  /findings/{findingId}/fix/stream:
    get:
      operationId: streamFixProgress
      summary: Stream fix progress via Server-Sent Events
      tags: [AI Fix]
      parameters:
        - $ref: "#/components/parameters/FindingId"
      responses:
        "200":
          description: SSE stream of fix progress events
          content:
            text/event-stream:
              schema:
                type: string

  # ─────────────────────────────────────────────
  # DAX Queries
  # ─────────────────────────────────────────────
  /dax/execute:
    post:
      operationId: executeDaxQuery
      summary: Execute a DAX query against the connected model
      tags: [DAX Queries]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/DaxQueryRequest"
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/DaxQueryResult"
        "400":
          description: Invalid DAX query
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "422":
          description: No model connected
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

  /dax/generate:
    post:
      operationId: generateDaxQuery
      summary: Generate a DAX query from natural language using AI
      tags: [DAX Queries]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [prompt]
              properties:
                prompt:
                  type: string
                  description: Natural language description of the desired query
                  example: "Show total sales by region for last year"
      responses:
        "200":
          content:
            application/json:
              schema:
                type: object
                properties:
                  query:
                    type: string
                    description: Generated DAX query
                  explanation:
                    type: string
                    description: AI explanation of the query

  /dax/history:
    get:
      operationId: getDaxHistory
      summary: Get DAX query execution history
      tags: [DAX Queries]
      parameters:
        - name: limit
          in: query
          schema:
            type: integer
            default: 20
        - name: offset
          in: query
          schema:
            type: integer
            default: 0
      responses:
        "200":
          content:
            application/json:
              schema:
                type: object
                properties:
                  queries:
                    type: array
                    items:
                      $ref: "#/components/schemas/DaxQuery"

  # ─────────────────────────────────────────────
  # Rules (reference)
  # ─────────────────────────────────────────────

  /dax/{queryId}/cancel:
    post:
      operationId: cancelDaxQuery
      summary: Cancel a running DAX query
      tags: [DAX Queries]
      parameters:
        - name: queryId
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Query cancelled
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
        "404":
          $ref: "#/components/responses/NotFound"
        "409":
          description: Query not running
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

  /rules:
    get:
      operationId: listRules
      summary: List all BPA rules
      tags: [Rules]
      parameters:
        - name: category
          in: query
          schema:
            type: string
      responses:
        "200":
          content:
            application/json:
              schema:
                type: object
                properties:
                  rules:
                    type: array
                    items:
                      $ref: "#/components/schemas/BpaRule"

# ═══════════════════════════════════════════════
# Components
# ═══════════════════════════════════════════════
components:
  parameters:
    RunId:
      name: runId
      in: path
      required: true
      schema:
        type: string
    FindingId:
      name: findingId
      in: path
      required: true
      schema:
        type: string

  responses:
    BadRequest:
      description: Invalid request
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorResponse"
    NotFound:
      description: Resource not found
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorResponse"

  schemas:
    # ── Connection ──
    PbiInstance:
      type: object
      properties:
        name:
          type: string
        serverAddress:
          type: string
        databaseName:
          type: string

    ConnectRequest:
      type: object
      required: [serverAddress, databaseName]
      properties:
        serverAddress:
          type: string
          description: "localhost:<port> of PBI Desktop instance"
        databaseName:
          type: string
          description: Database/model name within the instance

    ConnectionStatus:
      type: object
      properties:
        connected:
          type: boolean
        modelName:
          type: string
        serverAddress:
          type: string
        databaseName:
          type: string
        connectedAt:
          type: string
          format: date-time

    # ── Analysis ──
    AnalysisRun:
      type: object
      properties:
        id:
          type: string
        modelName:
          type: string
        status:
          type: string
          enum: [RUNNING, COMPLETED, FAILED]
        startedAt:
          type: string
          format: date-time
        completedAt:
          type: string
          format: date-time
          nullable: true
        errorCount:
          type: integer
        warningCount:
          type: integer
        infoCount:
          type: integer

    AnalysisRunDetail:
      allOf:
        - $ref: "#/components/schemas/AnalysisRun"
        - type: object
          properties:
            findings:
              type: array
              items:
                $ref: "#/components/schemas/Finding"
            summary:
              $ref: "#/components/schemas/FindingSummary"

    FindingSummary:
      type: object
      properties:
        totalCount:
          type: integer
        errorCount:
          type: integer
        warningCount:
          type: integer
        infoCount:
          type: integer
        fixedCount:
          type: integer
        unfixedCount:
          type: integer

    # ── Finding ──
    Finding:
      type: object
      properties:
        id:
          type: string
        ruleId:
          type: string
        ruleName:
          type: string
        category:
          type: string
        severity:
          type: integer
          description: "1=Info, 2=Warning, 3=Error"
        description:
          type: string
        affectedObject:
          type: string
        objectType:
          type: string
        fixStatus:
          type: string
          enum: [UNFIXED, IN_PROGRESS, FIXED, FAILED]
        fixSummary:
          type: string
          nullable: true
        hasAutoFix:
          type: boolean
        createdAt:
          type: string
          format: date-time

    FindingDetail:
      allOf:
        - $ref: "#/components/schemas/Finding"
        - type: object
          properties:
            fixSession:
              $ref: "#/components/schemas/FixSession"
              nullable: true

    # ── Fix Session ──
    FixSession:
      type: object
      properties:
        id:
          type: string
        findingId:
          type: string
        status:
          type: string
          enum: [PENDING, RUNNING, COMPLETED, FAILED]
        startedAt:
          type: string
          format: date-time
        completedAt:
          type: string
          format: date-time
          nullable: true

    FixSessionDetail:
      allOf:
        - $ref: "#/components/schemas/FixSession"
        - type: object
          properties:
            steps:
              type: array
              items:
                $ref: "#/components/schemas/FixSessionStep"

    FixSessionStep:
      type: object
      properties:
        id:
          type: string
        stepNumber:
          type: integer
        eventType:
          type: string
          enum: [reasoning, tool_call, tool_result, message, error]
        content:
          type: string
          description: JSON-encoded event data
        timestamp:
          type: string
          format: date-time

    # ── DAX ──
    DaxQueryRequest:
      type: object
      required: [query]
      properties:
        query:
          type: string
          description: DAX query to execute
          example: "EVALUATE 'Sales'"

    DaxQueryResult:
      type: object
      properties:
        id:
          type: string
        query:
          type: string
        status:
          type: string
          enum: [COMPLETED, FAILED]
        columns:
          type: array
          items:
            type: object
            properties:
              name:
                type: string
              dataType:
                type: string
        rows:
          type: array
          items:
            type: object
            additionalProperties: true
        rowCount:
          type: integer
        executionTimeMs:
          type: integer
        errorMessage:
          type: string
          nullable: true

    DaxQuery:
      type: object
      properties:
        id:
          type: string
        queryText:
          type: string
        naturalLanguage:
          type: string
          nullable: true
        status:
          type: string
        rowCount:
          type: integer
          nullable: true
        executionTimeMs:
          type: integer
          nullable: true
        errorMessage:
          type: string
          nullable: true
        createdAt:
          type: string
          format: date-time

    # ── Rules ──
    BpaRule:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        category:
          type: string
        description:
          type: string
        severity:
          type: integer
        scope:
          type: string
        hasFixExpression:
          type: boolean

    # ── Common ──
    ErrorResponse:
      type: object
      required: [error]
      properties:
        error:
          type: string
        details:
          type: string
